---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cs-pvs
  namespace: codeserver
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage

---
apiversion: apps/v1
kind: Deployment
metadata:
  name: cs-deploy
  namespace: codeserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codeserver
  template:
    metadata:
      labels:
        app: codeserver
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
      - name: workspace-vol
        persistentVolumeClaim:
          claimName: cs-pvc
      containers:
      - name: cs-container
        image: linuxserver/code-server@sha256:b0448d77791bc8fa30cc2ce2c983cbc8d5e7c7019d0c96034d14bffdc801004e
        imagePullPolicy: IfNotPresent
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        envFrom:
        - configMapRef:
            name: condeserver-cm
        - secretRef:
            name: codeserver-secret
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: workspace-vol
          mountPath: /config/workspace
        resources:
          requests:
            cpu: 200m
            memory: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: cs-svc
  namespace: codeserver
spec:
  type: ClusterIP
  selector:
    app: codeserver
  ports:
  - port: 8443
    targetPort: 8443

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cs-ing
  namespace: codeserver 
spec:
  ingressClassName: nginx
  rules:
  - host: cs-116.203.255.68.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cs-svc
            port:
              number: 8443