---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: default
spec:
  accessModes:
  #- ReadWriteMany
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  #storageClassName: do-block-storage # got from the "k get sc" storage classes
  storageClassName: do-block-storage-retain

---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-po
  namespace: default
spec:
  volumes:
  - name: data-vol
    persistentVolumeClaim:
      claimName: mysql-pvc
  containers:
  - name: mysql-container
    image: mysql:8
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: changeit
    ports:
     - containerPort: 3306
    volumeMounts:
    - name: data-vol
      mountPath: /var/lib/mysql
      readOnly: true
    resources: {}
