version: '3'
services:
  mydb:
    image: stackupiss/northwind-db:v1
    volumes:
      - mydb_data:/var/lib/mysql
    networks:
      - mynet

  myapp:
    image: stackupiss/northwind-app:v1
    environment:
      DB_HOST: mydb
      DB_USER: root
      DB_PASSWORD: changeit
    ports:
      - "8080:8080"
    networks:
      - mynet

networks:
  mynet:
    driver: bridge

volumes:
  mydb_data:
