---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dov-deploy
  namespace: myns
  labels:
    app: dov
    name: dov-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: myapp
      dept: eng
      commit: abc123
  template:
    metadata:
      name: mypod
      namespace: myns
      labels:
        app: myapp
        dept: eng
        commit: abc123
    spec:
      containers:
      - name: mypod-container
        image: ferdzzz/dov-bear-python@sha256:a67b13a9fbcdae1be261d97238457cb05d339eeb6f5dcd13eedd3bf68f30a9dc 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
         - name: INSTANCE_NAME
           value: my first pod
         - name: INSTANCE_HASH
           value: abc123

---
apiVersion: v1
kind: Service
metadata:
  name: dov-svc
  namespace: myns
  labels:
    app: dov
    name: dov-svc
spec:
  type: ClusterIP
  selector:
    app: myapp
    dept: eng
    commit: abc123
  ports:
  - port: 8000
    targetPort: 3000

