---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  namespace: bggns
  labels:
    app: bgg
    name: bggapp-deploy
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 4
  selector:
    matchLabels:
      app: bgg
      name: bggapp-po
  template:
   metadata:
      labels:
        app: bgg
        name: bggapp-po
   spec:
      containers:
      - name: bggapp-container
        image: stackupiss/bgg-backend:v2
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: bgg-cm
        - secretRef:
            name: bgg-secret
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
    name: bggapp-svc
    namespace: bggns
    labels:
      app: bgg
      name: bggapp-svc
spec:
  type: ClusterIP
  # type: NodePort
  # type: LoadBalancer
  selector:
    app: bgg
    name: bggapp-po
  ports:
  - port: 80
    targetPort: 3000
