---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggdb-deploy
  namespace: bggns
  labels:
    app: bgg-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bgg-database
  template:
    metadata:
      labels:
	app: bgg-database
    spec:
      containers:
	- name: bggdb-container
	  image: stackupiss/bgg-database:v1
	  ports:
	  - containerPort: 3306
