---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: bgg-gw
  namespace: bggns
  labels:
    app: bgg
    name: bgg-gw
spec:
  gatewayClassName: nginx
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    hostname: "*.116.203.255.68.nip.ip"


---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: bgg-httproute
  namespace: bggns
  labels:
    app: bgg
    name: bgg-httproute
spec:
  parentRefs:
  - name: bgg-gw
    sectionName: http
  hostname:
  - bgg.192.168.1.250.nip.ip
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: bggapp-svc
      port: 80